#!/usr/bin/python

import struct
import binhex
import math
import time
import random

# mouse location
file = open('dev/input/by-id/usb-Logitech_USB_Optical_Mouse-mouse','rb')

#radio stations
radiourl = [
    'http://ice6.somafm.com/groovesalad-16-aac',
    'http://ice2.somafm.com/dronezone-32-aac',
    'http://ice2.somafm.com/indiepop-32-aac',
    'http://ice2.somafm.com/spacestation-32-aac',
    'http://ice2.somafm.com/secretagent-32-aac',
    'http://ice2.somafm.com/lush-32-aac',
    'http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk',
    ]

def readmouse():
    f = open( "/dev/input/mice", "rb" );
    while 1:
        data = f.read(3)  # Reads the 3 bytes
        identity,x,y = struct.unpack('3b',data)  #Unpacks the bytes to integers
        print(str(x) + str(y)
#zone_size=50
#canvas_dimensions = (800,600)
#zones = []

# creates circular zones
#class Zone:
 #   def __init__(self, x, y, size):
  #      self.x = x
  #      self.y = y
 #       self.size = size

#create zones for each url added
#for x in radiourl:
 #     rndCor = (random.randint(zone_size/2, canvas_dimensions[0]), random.randint(zone_size/2, canvas_dimensions[1]))
 #     zones.append(zone(rndCor[0],rndCor[1],zone_size))
